"""
Django settings for syndication project.

Generated by 'django-admin startproject' using Django 1.11.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$ey=h@b(pyf%=nbpslfl8+-!0lqwx94sfq@y%1oi*#6i4g)+9x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

COMPANY_NAME = "SYNDICATION.com"
COMPANY_CONTACT = "rajtilak.pati@GMAIL.COM"


# Application definition

INSTALLED_APPS = [
    'accounts.apps.AccountsConfig',
    'publications.apps.PublicationsConfig',
    'content_management.apps.ContentManagementConfig',
    'cutils.apps.CutilsConfig',
    'chronograph.apps.ChronographConfig',
    'penseive.apps.PeneiveConfig',
    'penseive_entity.apps.PenseiveEntityConfig',
    'queues.apps.QueuesConfig',
    'royalties.apps.RoyalitiesConfig',
    #'press_release_stories.apps.PressReleaseConfig',
    'story.apps.StoryConfig',
    'websource.apps.WebsourceConfig',
    # 'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tinymce',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'syndication.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'syndication.wsgi.application'

DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.postgresql_psycopg2',
       'NAME': 'syndication_db',
       'USER': 'syndication',
       'PASSWORD': 'syndication',
       'HOST': '',
       'PORT': '',
   }
}

STRIP_TAGS = "span font div class html sup hr small"
# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = False

TINYMCE_DEFAULT_CONFIG = {
    'height': "400",
    'width': "840",
    'theme': "advanced", # default value
    #'plugins': "table,spellchecker,paste,searchreplace",
    'theme_advanced_buttons1': "newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,formatselect,fontselect,fontsizeselect,cut,copy,paste,pastetext,pasteword,search,replace,|,",
    # 'theme_advanced_buttons1': "styleselect,fontselect,fontsizeselect,sync,spellchecker,bold,italic,underline,separator,strikethrough,justifyleft,justifycenter,justifyright,justifyfull,bullist,numlist,separator,undo,redo,separator,link,unlink,image,code,tablecontrols",
    # 'theme_advanced_buttons2': "forecolor,backcolor", "theme_advanced_buttons3": "",
    "theme_advanced_buttons2": "bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor,sub,sup,|,charmap",
    "theme_advanced_buttons3": "",
    'theme_advanced_toolbar_location': "top",
    'theme_advanced_toolbar_align': "left",
    'theme_advanced_statusbar_location': "bottom",
    'relative_urls': False,
    'theme_advanced_path': True,
}
#TINYMCE_SPELLCHECKER = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

MEDIA_URL = '/media/'
STATIC_URL = '/static/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_ROOT = os.path.join(BASE_DIR, "static")
